// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CMD_ID_CHANNEL

typedef GPB_ENUM(CMD_ID_CHANNEL) {
  /** 查询频道详情 */
  CMD_ID_CHANNEL_C2SgetChannelInfoId = 3001,
  CMD_ID_CHANNEL_S2CgetChannelInfoId = 3002,

  /** 查询频道成员 */
  CMD_ID_CHANNEL_C2SgetChannelMemberId = 3003,
  CMD_ID_CHANNEL_S2CgetChannelMemberId = 3004,

  /** 创建频道 */
  CMD_ID_CHANNEL_C2ScreateChannelId = 3005,
  CMD_ID_CHANNEL_S2CcreateChannelId = 3006,
  CMD_ID_CHANNEL_S2CjoinChannelNoticeId = 3007,
  CMD_ID_CHANNEL_C2SjoinChannelNoticeId = 3008,

  /** 离开频道 */
  CMD_ID_CHANNEL_C2SdepartureChannelId = 3009,
  CMD_ID_CHANNEL_S2CdepartureChannelId = 3010,
  CMD_ID_CHANNEL_S2CdepartureChannelNoticeId = 3011,
  CMD_ID_CHANNEL_C2SdepartureChannelNoticeId = 3012,

  /** 踢出频道 */
  CMD_ID_CHANNEL_C2SkickChannelMemberId = 3013,
  CMD_ID_CHANNEL_S2CkickChannelMemberId = 3014,
  CMD_ID_CHANNEL_S2CkickChannelMemberNoticeId = 3015,
  CMD_ID_CHANNEL_C2SkickChannelMemberNoticeId = 3016,

  /** 销毁频道 */
  CMD_ID_CHANNEL_C2SdestroyChannelId = 3017,

  /** 销毁频道响应 */
  CMD_ID_CHANNEL_S2CdestroyChannelId = 3018,

  /** 频道即将销毁通知 */
  CMD_ID_CHANNEL_S2CdestroyChannelWarnNoticeId = 3019,

  /** 频道已销毁通知 */
  CMD_ID_CHANNEL_S2CdestroyChannelNoticeId = 3020,

  /** 邀请加入频道 */
  CMD_ID_CHANNEL_C2SinviteChannelMemberId = 3021,
  CMD_ID_CHANNEL_S2CinviteChannelMemberId = 3022,

  /** 被邀请加入频道通知 */
  CMD_ID_CHANNEL_S2CinviteChannelMemberNoticeId = 3023,

  /** 加入频道 */
  CMD_ID_CHANNEL_C2SjoinChannelId = 3025,
  CMD_ID_CHANNEL_S2CjoinChannelId = 3026,

  /** 修改频道名称 */
  CMD_ID_CHANNEL_C2SmodifyChannelNameId = 3027,
  CMD_ID_CHANNEL_S2CmodifyChannelNameId = 3028,
  CMD_ID_CHANNEL_S2CmodifyChannelNameNoticeId = 3029,
  CMD_ID_CHANNEL_C2SmodifyChannelNameNoticeId = 3030,

  /** 修改频道描述 */
  CMD_ID_CHANNEL_C2SmodifyChannelDescId = 3031,
  CMD_ID_CHANNEL_S2CmodifyChannelDescId = 3032,
  CMD_ID_CHANNEL_S2CmodifyChannelDescNoticeId = 3033,
  CMD_ID_CHANNEL_C2SmodifyChannelDescNoticeId = 3034,
};

GPBEnumDescriptor *CMD_ID_CHANNEL_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CMD_ID_CHANNEL_IsValidValue(int32_t value);

#pragma mark - ChannelRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ChannelRoot : GPBRootObject
@end

#pragma mark - C2SGetChannelTypeMsg

typedef GPB_ENUM(C2SGetChannelTypeMsg_FieldNumber) {
  C2SGetChannelTypeMsg_FieldNumber_PlayerId = 1,
  C2SGetChannelTypeMsg_FieldNumber_ChannelId = 2,
  C2SGetChannelTypeMsg_FieldNumber_ChannelCode = 3,
};

GPB_FINAL @interface C2SGetChannelTypeMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道ID */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道CODE */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

@end

#pragma mark - S2CGetChannelTypeMsg

typedef GPB_ENUM(S2CGetChannelTypeMsg_FieldNumber) {
  S2CGetChannelTypeMsg_FieldNumber_Code = 1,
  S2CGetChannelTypeMsg_FieldNumber_Msg = 2,
  S2CGetChannelTypeMsg_FieldNumber_Content = 4,
};

GPB_FINAL @interface S2CGetChannelTypeMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 返回频道详情 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - C2SGetChannelMemberMsg

typedef GPB_ENUM(C2SGetChannelMemberMsg_FieldNumber) {
  C2SGetChannelMemberMsg_FieldNumber_RequestId = 1,
  C2SGetChannelMemberMsg_FieldNumber_PlayerId = 2,
  C2SGetChannelMemberMsg_FieldNumber_ChannelId = 3,
  C2SGetChannelMemberMsg_FieldNumber_ChannelCode = 4,
};

GPB_FINAL @interface C2SGetChannelMemberMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道ID */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道CODE */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

@end

#pragma mark - S2CGetChannelMemberMsg

typedef GPB_ENUM(S2CGetChannelMemberMsg_FieldNumber) {
  S2CGetChannelMemberMsg_FieldNumber_Code = 1,
  S2CGetChannelMemberMsg_FieldNumber_Msg = 2,
  S2CGetChannelMemberMsg_FieldNumber_RequestId = 3,
  S2CGetChannelMemberMsg_FieldNumber_Content = 4,
};

GPB_FINAL @interface S2CGetChannelMemberMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 玩家ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 返回频道成员信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - C2SCreateChannelMsg

typedef GPB_ENUM(C2SCreateChannelMsg_FieldNumber) {
  C2SCreateChannelMsg_FieldNumber_RequestId = 1,
  C2SCreateChannelMsg_FieldNumber_PlayerId = 2,
  C2SCreateChannelMsg_FieldNumber_ChannelTypeCode = 3,
  C2SCreateChannelMsg_FieldNumber_ChannelName = 4,
  C2SCreateChannelMsg_FieldNumber_ChannelDesc = 5,
  C2SCreateChannelMsg_FieldNumber_MemberIds = 6,
};

GPB_FINAL @interface C2SCreateChannelMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道类目编码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelTypeCode;
/** Test to see if @c channelTypeCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelTypeCode;

/** 频道名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelName;
/** Test to see if @c channelName has been set. */
@property(nonatomic, readwrite) BOOL hasChannelName;

/** 频道描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelDesc;
/** Test to see if @c channelDesc has been set. */
@property(nonatomic, readwrite) BOOL hasChannelDesc;

/** 频道成员ID,逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberIds;
/** Test to see if @c memberIds has been set. */
@property(nonatomic, readwrite) BOOL hasMemberIds;

@end

#pragma mark - S2CCreateChannelMsg

typedef GPB_ENUM(S2CCreateChannelMsg_FieldNumber) {
  S2CCreateChannelMsg_FieldNumber_Code = 1,
  S2CCreateChannelMsg_FieldNumber_Msg = 2,
  S2CCreateChannelMsg_FieldNumber_RequestId = 3,
  S2CCreateChannelMsg_FieldNumber_ChannelId = 4,
  S2CCreateChannelMsg_FieldNumber_ChannelCode = 5,
};

GPB_FINAL @interface S2CCreateChannelMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 玩家ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 返回创建频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 返回创建频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

@end

#pragma mark - S2CJoinChannelNotice

typedef GPB_ENUM(S2CJoinChannelNotice_FieldNumber) {
  S2CJoinChannelNotice_FieldNumber_ChannelId = 1,
  S2CJoinChannelNotice_FieldNumber_ChannelCode = 2,
  S2CJoinChannelNotice_FieldNumber_MemberIds = 3,
  S2CJoinChannelNotice_FieldNumber_Inviter = 4,
  S2CJoinChannelNotice_FieldNumber_Content = 5,
};

GPB_FINAL @interface S2CJoinChannelNotice : GPBMessage

/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道编码，客户端无需关注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 频道成员ID，客户端无需关注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *memberIds;
/** Test to see if @c memberIds has been set. */
@property(nonatomic, readwrite) BOOL hasMemberIds;

/** 邀请人玩家ID，非必须 */
@property(nonatomic, readwrite) int64_t inviter;

@property(nonatomic, readwrite) BOOL hasInviter;
/** 频道信息(JSON数组) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - C2SDepartureChannelMsg

typedef GPB_ENUM(C2SDepartureChannelMsg_FieldNumber) {
  C2SDepartureChannelMsg_FieldNumber_RequestId = 1,
  C2SDepartureChannelMsg_FieldNumber_PlayerId = 2,
  C2SDepartureChannelMsg_FieldNumber_ChannelId = 3,
  C2SDepartureChannelMsg_FieldNumber_ChannelCode = 4,
};

GPB_FINAL @interface C2SDepartureChannelMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 返回创建频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 返回创建频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

@end

#pragma mark - S2CDepartureChannelMsg

typedef GPB_ENUM(S2CDepartureChannelMsg_FieldNumber) {
  S2CDepartureChannelMsg_FieldNumber_Code = 1,
  S2CDepartureChannelMsg_FieldNumber_Msg = 2,
  S2CDepartureChannelMsg_FieldNumber_RequestId = 3,
  S2CDepartureChannelMsg_FieldNumber_PlayerId = 4,
  S2CDepartureChannelMsg_FieldNumber_ChannelId = 5,
  S2CDepartureChannelMsg_FieldNumber_ChannelCode = 6,
};

GPB_FINAL @interface S2CDepartureChannelMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 玩家ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 返回创建频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 返回创建频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

@end

#pragma mark - S2CDepartureChannelNoticeMsg

typedef GPB_ENUM(S2CDepartureChannelNoticeMsg_FieldNumber) {
  S2CDepartureChannelNoticeMsg_FieldNumber_PlayerId = 1,
  S2CDepartureChannelNoticeMsg_FieldNumber_ChannelId = 2,
  S2CDepartureChannelNoticeMsg_FieldNumber_ChannelCode = 3,
};

GPB_FINAL @interface S2CDepartureChannelNoticeMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 返回创建频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 返回创建频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

@end

#pragma mark - C2SKickChannelMemberMsg

typedef GPB_ENUM(C2SKickChannelMemberMsg_FieldNumber) {
  C2SKickChannelMemberMsg_FieldNumber_RequestId = 1,
  C2SKickChannelMemberMsg_FieldNumber_PlayerId = 2,
  C2SKickChannelMemberMsg_FieldNumber_ChannelId = 3,
  C2SKickChannelMemberMsg_FieldNumber_ChannelCode = 4,
  C2SKickChannelMemberMsg_FieldNumber_TargetPlayerId = 5,
};

GPB_FINAL @interface C2SKickChannelMemberMsg : GPBMessage

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID */
@property(nonatomic, readwrite) int64_t targetPlayerId;

@property(nonatomic, readwrite) BOOL hasTargetPlayerId;
@end

#pragma mark - S2CKickChannelMemberMsg

typedef GPB_ENUM(S2CKickChannelMemberMsg_FieldNumber) {
  S2CKickChannelMemberMsg_FieldNumber_Code = 1,
  S2CKickChannelMemberMsg_FieldNumber_Msg = 2,
  S2CKickChannelMemberMsg_FieldNumber_RequestId = 3,
  S2CKickChannelMemberMsg_FieldNumber_PlayerId = 4,
  S2CKickChannelMemberMsg_FieldNumber_ChannelId = 5,
  S2CKickChannelMemberMsg_FieldNumber_ChannelCode = 6,
  S2CKickChannelMemberMsg_FieldNumber_TargetPlayerId = 7,
};

GPB_FINAL @interface S2CKickChannelMemberMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 玩家ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID */
@property(nonatomic, readwrite) int64_t targetPlayerId;

@property(nonatomic, readwrite) BOOL hasTargetPlayerId;
@end

#pragma mark - S2CKickChannelMemberNoticeMsg

typedef GPB_ENUM(S2CKickChannelMemberNoticeMsg_FieldNumber) {
  S2CKickChannelMemberNoticeMsg_FieldNumber_ChannelId = 1,
  S2CKickChannelMemberNoticeMsg_FieldNumber_ChannelCode = 2,
  S2CKickChannelMemberNoticeMsg_FieldNumber_TargetPlayerId = 3,
};

GPB_FINAL @interface S2CKickChannelMemberNoticeMsg : GPBMessage

/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID */
@property(nonatomic, readwrite) int64_t targetPlayerId;

@property(nonatomic, readwrite) BOOL hasTargetPlayerId;
@end

#pragma mark - C2SInviteChannelMemberMsg

typedef GPB_ENUM(C2SInviteChannelMemberMsg_FieldNumber) {
  C2SInviteChannelMemberMsg_FieldNumber_RequestId = 1,
  C2SInviteChannelMemberMsg_FieldNumber_PlayerId = 2,
  C2SInviteChannelMemberMsg_FieldNumber_ChannelId = 3,
  C2SInviteChannelMemberMsg_FieldNumber_ChannelCode = 4,
  C2SInviteChannelMemberMsg_FieldNumber_TargetPlayerIds = 5,
};

GPB_FINAL @interface C2SInviteChannelMemberMsg : GPBMessage

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetPlayerIds;
/** Test to see if @c targetPlayerIds has been set. */
@property(nonatomic, readwrite) BOOL hasTargetPlayerIds;

@end

#pragma mark - S2CInviteChannelMemberMsg

typedef GPB_ENUM(S2CInviteChannelMemberMsg_FieldNumber) {
  S2CInviteChannelMemberMsg_FieldNumber_Code = 1,
  S2CInviteChannelMemberMsg_FieldNumber_Msg = 2,
  S2CInviteChannelMemberMsg_FieldNumber_RequestId = 3,
  S2CInviteChannelMemberMsg_FieldNumber_PlayerId = 4,
  S2CInviteChannelMemberMsg_FieldNumber_ChannelId = 5,
  S2CInviteChannelMemberMsg_FieldNumber_ChannelCode = 6,
  S2CInviteChannelMemberMsg_FieldNumber_TargetPlayerIds = 7,
};

GPB_FINAL @interface S2CInviteChannelMemberMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targetPlayerIds;
/** Test to see if @c targetPlayerIds has been set. */
@property(nonatomic, readwrite) BOOL hasTargetPlayerIds;

@end

#pragma mark - S2CInviteChannelMemberNoticeMsg

typedef GPB_ENUM(S2CInviteChannelMemberNoticeMsg_FieldNumber) {
  S2CInviteChannelMemberNoticeMsg_FieldNumber_PlayerId = 1,
  S2CInviteChannelMemberNoticeMsg_FieldNumber_ChannelId = 2,
  S2CInviteChannelMemberNoticeMsg_FieldNumber_ChannelCode = 3,
  S2CInviteChannelMemberNoticeMsg_FieldNumber_Inviter = 4,
  S2CInviteChannelMemberNoticeMsg_FieldNumber_Content = 5,
};

GPB_FINAL @interface S2CInviteChannelMemberNoticeMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID，多个逗号拼接 */
@property(nonatomic, readwrite) int64_t inviter;

@property(nonatomic, readwrite) BOOL hasInviter;
/** 频道信息(JSON数组) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - C2SJoinChannelMsg

typedef GPB_ENUM(C2SJoinChannelMsg_FieldNumber) {
  C2SJoinChannelMsg_FieldNumber_RequestId = 1,
  C2SJoinChannelMsg_FieldNumber_PlayerId = 2,
  C2SJoinChannelMsg_FieldNumber_ChannelId = 3,
  C2SJoinChannelMsg_FieldNumber_ChannelCode = 4,
  C2SJoinChannelMsg_FieldNumber_Inviter = 5,
};

GPB_FINAL @interface C2SJoinChannelMsg : GPBMessage

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID */
@property(nonatomic, readwrite) int64_t inviter;

@property(nonatomic, readwrite) BOOL hasInviter;
@end

#pragma mark - S2CJoinChannelMsg

typedef GPB_ENUM(S2CJoinChannelMsg_FieldNumber) {
  S2CJoinChannelMsg_FieldNumber_Code = 1,
  S2CJoinChannelMsg_FieldNumber_Msg = 2,
  S2CJoinChannelMsg_FieldNumber_RequestId = 3,
  S2CJoinChannelMsg_FieldNumber_PlayerId = 4,
  S2CJoinChannelMsg_FieldNumber_ChannelId = 5,
  S2CJoinChannelMsg_FieldNumber_ChannelCode = 6,
  S2CJoinChannelMsg_FieldNumber_Inviter = 7,
};

GPB_FINAL @interface S2CJoinChannelMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 邀请人玩家ID，非必须 */
@property(nonatomic, readwrite) int64_t inviter;

@property(nonatomic, readwrite) BOOL hasInviter;
@end

#pragma mark - C2SModifyChannelNameMsg

typedef GPB_ENUM(C2SModifyChannelNameMsg_FieldNumber) {
  C2SModifyChannelNameMsg_FieldNumber_RequestId = 1,
  C2SModifyChannelNameMsg_FieldNumber_PlayerId = 2,
  C2SModifyChannelNameMsg_FieldNumber_ChannelId = 3,
  C2SModifyChannelNameMsg_FieldNumber_ChannelCode = 4,
  C2SModifyChannelNameMsg_FieldNumber_ChannelName = 5,
};

GPB_FINAL @interface C2SModifyChannelNameMsg : GPBMessage

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 修改名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelName;
/** Test to see if @c channelName has been set. */
@property(nonatomic, readwrite) BOOL hasChannelName;

@end

#pragma mark - S2CModifyChannelNameMsg

typedef GPB_ENUM(S2CModifyChannelNameMsg_FieldNumber) {
  S2CModifyChannelNameMsg_FieldNumber_Code = 1,
  S2CModifyChannelNameMsg_FieldNumber_Msg = 2,
  S2CModifyChannelNameMsg_FieldNumber_RequestId = 3,
  S2CModifyChannelNameMsg_FieldNumber_PlayerId = 4,
  S2CModifyChannelNameMsg_FieldNumber_ChannelId = 5,
  S2CModifyChannelNameMsg_FieldNumber_ChannelCode = 6,
  S2CModifyChannelNameMsg_FieldNumber_ChannelName = 7,
};

GPB_FINAL @interface S2CModifyChannelNameMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelName;
/** Test to see if @c channelName has been set. */
@property(nonatomic, readwrite) BOOL hasChannelName;

@end

#pragma mark - S2CModifyChannelNameNoticeMsg

typedef GPB_ENUM(S2CModifyChannelNameNoticeMsg_FieldNumber) {
  S2CModifyChannelNameNoticeMsg_FieldNumber_PlayerId = 1,
  S2CModifyChannelNameNoticeMsg_FieldNumber_ChannelId = 2,
  S2CModifyChannelNameNoticeMsg_FieldNumber_ChannelCode = 3,
  S2CModifyChannelNameNoticeMsg_FieldNumber_ChannelName = 4,
  S2CModifyChannelNameNoticeMsg_FieldNumber_ModifierId = 5,
  S2CModifyChannelNameNoticeMsg_FieldNumber_ModifierRoleName = 6,
  S2CModifyChannelNameNoticeMsg_FieldNumber_ModifierNickName = 7,
};

GPB_FINAL @interface S2CModifyChannelNameNoticeMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelName;
/** Test to see if @c channelName has been set. */
@property(nonatomic, readwrite) BOOL hasChannelName;

/** 修改名称玩家ID */
@property(nonatomic, readwrite) int64_t modifierId;

@property(nonatomic, readwrite) BOOL hasModifierId;
/** 修改名称玩家角色名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *modifierRoleName;
/** Test to see if @c modifierRoleName has been set. */
@property(nonatomic, readwrite) BOOL hasModifierRoleName;

/** 修改名称玩家频道昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *modifierNickName;
/** Test to see if @c modifierNickName has been set. */
@property(nonatomic, readwrite) BOOL hasModifierNickName;

@end

#pragma mark - C2SModifyChannelDescMsg

typedef GPB_ENUM(C2SModifyChannelDescMsg_FieldNumber) {
  C2SModifyChannelDescMsg_FieldNumber_RequestId = 1,
  C2SModifyChannelDescMsg_FieldNumber_PlayerId = 2,
  C2SModifyChannelDescMsg_FieldNumber_ChannelId = 3,
  C2SModifyChannelDescMsg_FieldNumber_ChannelCode = 4,
  C2SModifyChannelDescMsg_FieldNumber_ChannelDesc = 5,
};

GPB_FINAL @interface C2SModifyChannelDescMsg : GPBMessage

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 修改名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelDesc;
/** Test to see if @c channelDesc has been set. */
@property(nonatomic, readwrite) BOOL hasChannelDesc;

@end

#pragma mark - S2CModifyChannelDescMsg

typedef GPB_ENUM(S2CModifyChannelDescMsg_FieldNumber) {
  S2CModifyChannelDescMsg_FieldNumber_Code = 1,
  S2CModifyChannelDescMsg_FieldNumber_Msg = 2,
  S2CModifyChannelDescMsg_FieldNumber_RequestId = 3,
  S2CModifyChannelDescMsg_FieldNumber_PlayerId = 4,
  S2CModifyChannelDescMsg_FieldNumber_ChannelId = 5,
  S2CModifyChannelDescMsg_FieldNumber_ChannelCode = 6,
  S2CModifyChannelDescMsg_FieldNumber_ChannelDesc = 7,
};

GPB_FINAL @interface S2CModifyChannelDescMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 客户端请求ID */
@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite) BOOL hasRequestId;
/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelDesc;
/** Test to see if @c channelDesc has been set. */
@property(nonatomic, readwrite) BOOL hasChannelDesc;

@end

#pragma mark - S2CModifyChannelDescNoticeMsg

typedef GPB_ENUM(S2CModifyChannelDescNoticeMsg_FieldNumber) {
  S2CModifyChannelDescNoticeMsg_FieldNumber_PlayerId = 1,
  S2CModifyChannelDescNoticeMsg_FieldNumber_ChannelId = 2,
  S2CModifyChannelDescNoticeMsg_FieldNumber_ChannelCode = 3,
  S2CModifyChannelDescNoticeMsg_FieldNumber_ChannelDesc = 4,
  S2CModifyChannelDescNoticeMsg_FieldNumber_ModifierId = 5,
  S2CModifyChannelDescNoticeMsg_FieldNumber_ModifierRoleName = 6,
  S2CModifyChannelDescNoticeMsg_FieldNumber_ModifierNickName = 7,
};

GPB_FINAL @interface S2CModifyChannelDescNoticeMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道Id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 目标玩家ID，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelDesc;
/** Test to see if @c channelDesc has been set. */
@property(nonatomic, readwrite) BOOL hasChannelDesc;

/** 修改描述玩家ID */
@property(nonatomic, readwrite) int64_t modifierId;

@property(nonatomic, readwrite) BOOL hasModifierId;
/** 修改描述玩家角色名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *modifierRoleName;
/** Test to see if @c modifierRoleName has been set. */
@property(nonatomic, readwrite) BOOL hasModifierRoleName;

/** 修改描述玩家频道昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *modifierNickName;
/** Test to see if @c modifierNickName has been set. */
@property(nonatomic, readwrite) BOOL hasModifierNickName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
