// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CMD_ID_CHAT

typedef GPB_ENUM(CMD_ID_CHAT) {
  /** 私聊消息请求 */
  CMD_ID_CHAT_C2SprivateChatMsgId = 2001,

  /** 私聊消息响应 */
  CMD_ID_CHAT_S2CprivateChatMsgId = 2002,

  /** 私聊消息通知 */
  CMD_ID_CHAT_S2CprivateChatNoticeId = 2003,

  /** 私聊消息通知回复 */
  CMD_ID_CHAT_C2SprivateChatNoticeId = 2004,

  /** 群聊消息请求 */
  CMD_ID_CHAT_C2SgroupChatMsgId = 2005,

  /** 群聊消息响应 */
  CMD_ID_CHAT_S2CgroupChatMsgId = 2006,

  /** 群聊消息通知 */
  CMD_ID_CHAT_S2CgroupChatNoticeId = 2007,

  /** 群聊消息通知回复 */
  CMD_ID_CHAT_C2GroupChatNoticeId = 2008,
};

GPBEnumDescriptor *CMD_ID_CHAT_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CMD_ID_CHAT_IsValidValue(int32_t value);

#pragma mark - ChatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ChatRoot : GPBRootObject
@end

#pragma mark - C2SPrivateChatMsg

typedef GPB_ENUM(C2SPrivateChatMsg_FieldNumber) {
  C2SPrivateChatMsg_FieldNumber_ClientMsgId = 1,
  C2SPrivateChatMsg_FieldNumber_ClientSendTime = 2,
  C2SPrivateChatMsg_FieldNumber_SenderType = 3,
  C2SPrivateChatMsg_FieldNumber_FromPlayerId = 4,
  C2SPrivateChatMsg_FieldNumber_BusinessType = 5,
  C2SPrivateChatMsg_FieldNumber_ToPlayerId = 6,
  C2SPrivateChatMsg_FieldNumber_MsgType = 7,
  C2SPrivateChatMsg_FieldNumber_MsgBody = 8,
  C2SPrivateChatMsg_FieldNumber_ExtensionInfo = 9,
  C2SPrivateChatMsg_FieldNumber_ServerReceiveTime = 10,
};

GPB_FINAL @interface C2SPrivateChatMsg : GPBMessage

/** 客户端消息id，用于确认消息响应（有序） */
@property(nonatomic, readwrite) int64_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
/** 客户端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t clientSendTime;

@property(nonatomic, readwrite) BOOL hasClientSendTime;
/** 发送方类型 1：玩家 2：系统 */
@property(nonatomic, readwrite) int32_t senderType;

@property(nonatomic, readwrite) BOOL hasSenderType;
/** 用户id */
@property(nonatomic, readwrite) int64_t fromPlayerId;

@property(nonatomic, readwrite) BOOL hasFromPlayerId;
/** 业务类型  1:IM  2:游戏 */
@property(nonatomic, readwrite) int32_t businessType;

@property(nonatomic, readwrite) BOOL hasBusinessType;
/** 接收玩家id */
@property(nonatomic, readwrite) int64_t toPlayerId;

@property(nonatomic, readwrite) BOOL hasToPlayerId;
/** 消息类型 TEXT | IMAGE | VOICE | VIDEO */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;
/** Test to see if @c msgType has been set. */
@property(nonatomic, readwrite) BOOL hasMsgType;

/** 消息体 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;
/** Test to see if @c msgBody has been set. */
@property(nonatomic, readwrite) BOOL hasMsgBody;

/** 扩展消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extensionInfo;
/** Test to see if @c extensionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtensionInfo;

/** 服务端接收时间，客户端无需关注 */
@property(nonatomic, readwrite) int32_t serverReceiveTime;

@property(nonatomic, readwrite) BOOL hasServerReceiveTime;
@end

#pragma mark - S2CPrivateChatMsg

typedef GPB_ENUM(S2CPrivateChatMsg_FieldNumber) {
  S2CPrivateChatMsg_FieldNumber_Code = 1,
  S2CPrivateChatMsg_FieldNumber_Msg = 2,
  S2CPrivateChatMsg_FieldNumber_FromPlayerId = 3,
  S2CPrivateChatMsg_FieldNumber_ToPlayerId = 4,
  S2CPrivateChatMsg_FieldNumber_ClientMsgId = 5,
  S2CPrivateChatMsg_FieldNumber_ServerMsgId = 6,
  S2CPrivateChatMsg_FieldNumber_ClientSendTime = 7,
  S2CPrivateChatMsg_FieldNumber_ServerReceiveTime = 8,
  S2CPrivateChatMsg_FieldNumber_ServerSendTime = 9,
};

GPB_FINAL @interface S2CPrivateChatMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 用户id */
@property(nonatomic, readwrite) int64_t fromPlayerId;

@property(nonatomic, readwrite) BOOL hasFromPlayerId;
/** 用户id */
@property(nonatomic, readwrite) int64_t toPlayerId;

@property(nonatomic, readwrite) BOOL hasToPlayerId;
/** 客户端消息id */
@property(nonatomic, readwrite) int64_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
/** 服务端消息id（全局有序？频道有序） */
@property(nonatomic, readwrite) int64_t serverMsgId;

@property(nonatomic, readwrite) BOOL hasServerMsgId;
/** 客户端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t clientSendTime;

@property(nonatomic, readwrite) BOOL hasClientSendTime;
/** 服务端接收时间戳（秒） */
@property(nonatomic, readwrite) int32_t serverReceiveTime;

@property(nonatomic, readwrite) BOOL hasServerReceiveTime;
/** 服务端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t serverSendTime;

@property(nonatomic, readwrite) BOOL hasServerSendTime;
@end

#pragma mark - S2CPrivateChatNotice

typedef GPB_ENUM(S2CPrivateChatNotice_FieldNumber) {
  S2CPrivateChatNotice_FieldNumber_ClientMsgId = 1,
  S2CPrivateChatNotice_FieldNumber_ClientSendTime = 2,
  S2CPrivateChatNotice_FieldNumber_SenderType = 3,
  S2CPrivateChatNotice_FieldNumber_FromPlayerId = 4,
  S2CPrivateChatNotice_FieldNumber_FromPlayerRoleName = 5,
  S2CPrivateChatNotice_FieldNumber_FromPlayerNickName = 6,
  S2CPrivateChatNotice_FieldNumber_FromPlayerPortrait = 7,
  S2CPrivateChatNotice_FieldNumber_BusinessType = 8,
  S2CPrivateChatNotice_FieldNumber_ToPlayerId = 9,
  S2CPrivateChatNotice_FieldNumber_MsgType = 10,
  S2CPrivateChatNotice_FieldNumber_MsgBody = 11,
  S2CPrivateChatNotice_FieldNumber_ExtensionInfo = 12,
  S2CPrivateChatNotice_FieldNumber_ServerSendTime = 13,
};

GPB_FINAL @interface S2CPrivateChatNotice : GPBMessage

/** 客户端消息id，用于确认消息响应（有序） */
@property(nonatomic, readwrite) int64_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
/** 客户端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t clientSendTime;

@property(nonatomic, readwrite) BOOL hasClientSendTime;
/** 发送方类型 1：玩家 2：系统 */
@property(nonatomic, readwrite) int32_t senderType;

@property(nonatomic, readwrite) BOOL hasSenderType;
/** 用户id */
@property(nonatomic, readwrite) int64_t fromPlayerId;

@property(nonatomic, readwrite) BOOL hasFromPlayerId;
/** 用户角色名，客户端无需关注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromPlayerRoleName;
/** Test to see if @c fromPlayerRoleName has been set. */
@property(nonatomic, readwrite) BOOL hasFromPlayerRoleName;

/** 用户角色昵称，客户端无需关注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromPlayerNickName;
/** Test to see if @c fromPlayerNickName has been set. */
@property(nonatomic, readwrite) BOOL hasFromPlayerNickName;

/** 用户头像，客户端无需关注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromPlayerPortrait;
/** Test to see if @c fromPlayerPortrait has been set. */
@property(nonatomic, readwrite) BOOL hasFromPlayerPortrait;

/** 业务类型  1:IM  2:游戏 */
@property(nonatomic, readwrite) int32_t businessType;

@property(nonatomic, readwrite) BOOL hasBusinessType;
/** 接收玩家id */
@property(nonatomic, readwrite) int64_t toPlayerId;

@property(nonatomic, readwrite) BOOL hasToPlayerId;
/** 消息类型 TEXT | IMAGE | VOICE | VIDEO */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;
/** Test to see if @c msgType has been set. */
@property(nonatomic, readwrite) BOOL hasMsgType;

/** 消息体 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;
/** Test to see if @c msgBody has been set. */
@property(nonatomic, readwrite) BOOL hasMsgBody;

/** 扩展消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extensionInfo;
/** Test to see if @c extensionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtensionInfo;

/** 服务端接收时间，客户端无需关注 */
@property(nonatomic, readwrite) int32_t serverSendTime;

@property(nonatomic, readwrite) BOOL hasServerSendTime;
@end

#pragma mark - C2SGroupChatMsg

typedef GPB_ENUM(C2SGroupChatMsg_FieldNumber) {
  C2SGroupChatMsg_FieldNumber_ClientMsgId = 1,
  C2SGroupChatMsg_FieldNumber_ClientSendTime = 2,
  C2SGroupChatMsg_FieldNumber_SenderType = 3,
  C2SGroupChatMsg_FieldNumber_FromPlayerId = 4,
  C2SGroupChatMsg_FieldNumber_AtPlayerIds = 5,
  C2SGroupChatMsg_FieldNumber_BusinessType = 6,
  C2SGroupChatMsg_FieldNumber_ChannelId = 7,
  C2SGroupChatMsg_FieldNumber_ChannelCode = 8,
  C2SGroupChatMsg_FieldNumber_MsgType = 9,
  C2SGroupChatMsg_FieldNumber_MsgBody = 10,
  C2SGroupChatMsg_FieldNumber_ExtensionInfo = 11,
  C2SGroupChatMsg_FieldNumber_ServerReceiveTime = 12,
};

GPB_FINAL @interface C2SGroupChatMsg : GPBMessage

/** 客户端消息id，用于确认消息响应（有序） */
@property(nonatomic, readwrite) int64_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
/** 客户端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t clientSendTime;

@property(nonatomic, readwrite) BOOL hasClientSendTime;
/** 发送方类型 1：玩家（默认）  2：系统 */
@property(nonatomic, readwrite) int32_t senderType;

@property(nonatomic, readwrite) BOOL hasSenderType;
/** 用户id */
@property(nonatomic, readwrite) int64_t fromPlayerId;

@property(nonatomic, readwrite) BOOL hasFromPlayerId;
/** \@玩家id，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *atPlayerIds;
/** Test to see if @c atPlayerIds has been set. */
@property(nonatomic, readwrite) BOOL hasAtPlayerIds;

/** 业务类型  1:IM（默认）  2:游戏 */
@property(nonatomic, readwrite) int32_t businessType;

@property(nonatomic, readwrite) BOOL hasBusinessType;
/** 频道Code */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 消息类型 TEXT | IMAGE | VOICE | VIDEO */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;
/** Test to see if @c msgType has been set. */
@property(nonatomic, readwrite) BOOL hasMsgType;

/** 消息体 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;
/** Test to see if @c msgBody has been set. */
@property(nonatomic, readwrite) BOOL hasMsgBody;

/** 扩展消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extensionInfo;
/** Test to see if @c extensionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtensionInfo;

/** 服务端接收时间，客户端无需关注 */
@property(nonatomic, readwrite) int32_t serverReceiveTime;

@property(nonatomic, readwrite) BOOL hasServerReceiveTime;
@end

#pragma mark - S2CGroupChatMsg

typedef GPB_ENUM(S2CGroupChatMsg_FieldNumber) {
  S2CGroupChatMsg_FieldNumber_Code = 1,
  S2CGroupChatMsg_FieldNumber_Msg = 2,
  S2CGroupChatMsg_FieldNumber_FromPlayerId = 3,
  S2CGroupChatMsg_FieldNumber_ChannelId = 4,
  S2CGroupChatMsg_FieldNumber_ChannelCode = 5,
  S2CGroupChatMsg_FieldNumber_ClientMsgId = 6,
  S2CGroupChatMsg_FieldNumber_ServerMsgId = 7,
  S2CGroupChatMsg_FieldNumber_ClientSendTime = 8,
  S2CGroupChatMsg_FieldNumber_ServerReceiveTime = 9,
  S2CGroupChatMsg_FieldNumber_ServerSendTime = 10,
};

GPB_FINAL @interface S2CGroupChatMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 用户id */
@property(nonatomic, readwrite) int64_t fromPlayerId;

@property(nonatomic, readwrite) BOOL hasFromPlayerId;
/** 群聊id */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 群聊Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 客户端消息id */
@property(nonatomic, readwrite) int64_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
/** 服务端消息id（全局有序？频道有序） */
@property(nonatomic, readwrite) int64_t serverMsgId;

@property(nonatomic, readwrite) BOOL hasServerMsgId;
/** 客户端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t clientSendTime;

@property(nonatomic, readwrite) BOOL hasClientSendTime;
/** 服务端接收时间戳（秒） */
@property(nonatomic, readwrite) int32_t serverReceiveTime;

@property(nonatomic, readwrite) BOOL hasServerReceiveTime;
/** 服务端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t serverSendTime;

@property(nonatomic, readwrite) BOOL hasServerSendTime;
@end

#pragma mark - S2CGroupChatNotice

typedef GPB_ENUM(S2CGroupChatNotice_FieldNumber) {
  S2CGroupChatNotice_FieldNumber_ClientMsgId = 1,
  S2CGroupChatNotice_FieldNumber_ClientSendTime = 2,
  S2CGroupChatNotice_FieldNumber_SenderType = 3,
  S2CGroupChatNotice_FieldNumber_FromPlayerId = 4,
  S2CGroupChatNotice_FieldNumber_FromPlayerInfo = 5,
  S2CGroupChatNotice_FieldNumber_AtPlayerIds = 6,
  S2CGroupChatNotice_FieldNumber_BusinessType = 7,
  S2CGroupChatNotice_FieldNumber_ChannelId = 9,
  S2CGroupChatNotice_FieldNumber_ChannelCode = 10,
  S2CGroupChatNotice_FieldNumber_MsgType = 11,
  S2CGroupChatNotice_FieldNumber_MsgBody = 12,
  S2CGroupChatNotice_FieldNumber_ExtensionInfo = 13,
  S2CGroupChatNotice_FieldNumber_ServerMsgId = 14,
  S2CGroupChatNotice_FieldNumber_ServerSendTime = 15,
};

GPB_FINAL @interface S2CGroupChatNotice : GPBMessage

/** 客户端消息id，用于确认消息响应（有序） */
@property(nonatomic, readwrite) int64_t clientMsgId;

@property(nonatomic, readwrite) BOOL hasClientMsgId;
/** 客户端发出时间戳（秒） */
@property(nonatomic, readwrite) int32_t clientSendTime;

@property(nonatomic, readwrite) BOOL hasClientSendTime;
/** 发送方类型  1：玩家  2：系统 */
@property(nonatomic, readwrite) int32_t senderType;

@property(nonatomic, readwrite) BOOL hasSenderType;
/** 用户id */
@property(nonatomic, readwrite) int64_t fromPlayerId;

@property(nonatomic, readwrite) BOOL hasFromPlayerId;
/** 发送方展示信息，JSON字段方便扩展[{"roleName":"","nickName":"","portrait":""}] */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromPlayerInfo;
/** Test to see if @c fromPlayerInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFromPlayerInfo;

/** \@玩家id，多个逗号拼接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *atPlayerIds;
/** Test to see if @c atPlayerIds has been set. */
@property(nonatomic, readwrite) BOOL hasAtPlayerIds;

/** 业务类型  1:IM  2:游戏 */
@property(nonatomic, readwrite) int32_t businessType;

@property(nonatomic, readwrite) BOOL hasBusinessType;
/** 频道Code */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道Code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 消息类型 TEXT | IMAGE | VOICE | VIDEO */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;
/** Test to see if @c msgType has been set. */
@property(nonatomic, readwrite) BOOL hasMsgType;

/** 消息体 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgBody;
/** Test to see if @c msgBody has been set. */
@property(nonatomic, readwrite) BOOL hasMsgBody;

/** 扩展消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *extensionInfo;
/** Test to see if @c extensionInfo has been set. */
@property(nonatomic, readwrite) BOOL hasExtensionInfo;

/** 服务端消息id（全局有序？频道有序） */
@property(nonatomic, readwrite) int64_t serverMsgId;

@property(nonatomic, readwrite) BOOL hasServerMsgId;
/** 服务端接收时间，客户端无需关注 */
@property(nonatomic, readwrite) int32_t serverSendTime;

@property(nonatomic, readwrite) BOOL hasServerSendTime;
@end

#pragma mark - C2SGroupChatNotice

typedef GPB_ENUM(C2SGroupChatNotice_FieldNumber) {
  C2SGroupChatNotice_FieldNumber_PlayerId = 1,
  C2SGroupChatNotice_FieldNumber_ChannelId = 2,
  C2SGroupChatNotice_FieldNumber_ChannelCode = 3,
  C2SGroupChatNotice_FieldNumber_ServerMsgId = 4,
  C2SGroupChatNotice_FieldNumber_ClientReceiveTime = 5,
};

GPB_FINAL @interface C2SGroupChatNotice : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 频道编码 */
@property(nonatomic, readwrite) int64_t channelId;

@property(nonatomic, readwrite) BOOL hasChannelId;
/** 频道编码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCode;
/** Test to see if @c channelCode has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCode;

/** 服务端消息id */
@property(nonatomic, readwrite) int64_t serverMsgId;

@property(nonatomic, readwrite) BOOL hasServerMsgId;
/** 客户端接收时间 */
@property(nonatomic, readwrite) int64_t clientReceiveTime;

@property(nonatomic, readwrite) BOOL hasClientReceiveTime;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
