// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CMD_ID

typedef GPB_ENUM(CMD_ID) {
  /** 玩家登陆请求 */
  CMD_ID_C2SloginInMsgId = 1001,

  /** 玩家登陆响应 */
  CMD_ID_S2CloginMsgId = 1002,

  /** 玩家心跳请求 */
  CMD_ID_C2SpingMsgId = 1003,

  /** 玩家心跳响应 */
  CMD_ID_S2CpongMsgId = 1004,

  /** 玩家获取消息记录请求 */
  CMD_ID_C2SgetRecordMsgId = 1005,

  /** 玩家获取消息记录响应 */
  CMD_ID_S2CgetRecordMsgId = 1006,

  /** 用户登出 */
  CMD_ID_C2SlogoutMsgId = 1008,
};

GPBEnumDescriptor *CMD_ID_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CMD_ID_IsValidValue(int32_t value);

#pragma mark - LoginRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface LoginRoot : GPBRootObject
@end

#pragma mark - C2SLoginInMsg

typedef GPB_ENUM(C2SLoginInMsg_FieldNumber) {
  C2SLoginInMsg_FieldNumber_PlayerId = 1,
  C2SLoginInMsg_FieldNumber_Token = 2,
};

GPB_FINAL @interface C2SLoginInMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 验证TOKEN */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

@end

#pragma mark - S2CLoginMsg

typedef GPB_ENUM(S2CLoginMsg_FieldNumber) {
  S2CLoginMsg_FieldNumber_Code = 1,
  S2CLoginMsg_FieldNumber_Msg = 2,
  S2CLoginMsg_FieldNumber_PlayerId = 3,
};

GPB_FINAL @interface S2CLoginMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
@end

#pragma mark - C2SPingMsg

typedef GPB_ENUM(C2SPingMsg_FieldNumber) {
  C2SPingMsg_FieldNumber_TimeCurr = 1,
};

GPB_FINAL @interface C2SPingMsg : GPBMessage

/** 返回个时间戳 */
@property(nonatomic, readwrite) int64_t timeCurr;

@property(nonatomic, readwrite) BOOL hasTimeCurr;
@end

#pragma mark - S2CPongMsg

typedef GPB_ENUM(S2CPongMsg_FieldNumber) {
  S2CPongMsg_FieldNumber_TimeCurr = 1,
};

GPB_FINAL @interface S2CPongMsg : GPBMessage

/** 返回个时间戳 */
@property(nonatomic, readwrite) int64_t timeCurr;

@property(nonatomic, readwrite) BOOL hasTimeCurr;
@end

#pragma mark - C2SGetRecordMsg

typedef GPB_ENUM(C2SGetRecordMsg_FieldNumber) {
  C2SGetRecordMsg_FieldNumber_PlayerId = 1,
  C2SGetRecordMsg_FieldNumber_Index = 2,
};

GPB_FINAL @interface C2SGetRecordMsg : GPBMessage

/** 玩家获取频道消息请求 */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
/** 玩家本地索引数据，JSON串,如：{"world_01":211,"system_01":10} */
@property(nonatomic, readwrite, copy, null_resettable) NSString *index;
/** Test to see if @c index has been set. */
@property(nonatomic, readwrite) BOOL hasIndex;

@end

#pragma mark - S2CGetRecordMsg

typedef GPB_ENUM(S2CGetRecordMsg_FieldNumber) {
  S2CGetRecordMsg_FieldNumber_Code = 1,
  S2CGetRecordMsg_FieldNumber_Msg = 2,
  S2CGetRecordMsg_FieldNumber_Content = 3,
  S2CGetRecordMsg_FieldNumber_ChannelCodes = 4,
};

GPB_FINAL @interface S2CGetRecordMsg : GPBMessage

/** 返回值 成功 1 失败 0 */
@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite) BOOL hasCode;
/** 返回消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;
/** Test to see if @c msg has been set. */
@property(nonatomic, readwrite) BOOL hasMsg;

/** 频道消息(JSON数组) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

/** 玩家所有频道code,客户端无需关注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *channelCodes;
/** Test to see if @c channelCodes has been set. */
@property(nonatomic, readwrite) BOOL hasChannelCodes;

@end

#pragma mark - C2SLogoutMsg

typedef GPB_ENUM(C2SLogoutMsg_FieldNumber) {
  C2SLogoutMsg_FieldNumber_PlayerId = 1,
};

GPB_FINAL @interface C2SLogoutMsg : GPBMessage

/** 玩家ID */
@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite) BOOL hasPlayerId;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
